---
title: "Character Creation"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Character Creation}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)

```

```{r setup}
library(courtr)
library(magick)
library(rsvg)
```

Characters can be viewed and edited through the `Edit_Figures()` function.
This function will open an RShiny app that allows for the customization of characters.
The available character outfits and faces are shown below.

```{r study-outfits, echo=FALSE, message=FALSE, warning=FALSE, out.width = "24%", fig.show="hold", fig.ncol=3}

magick::image_ggplot(magick::image_read_svg(system.file("figures", "analyst.svg", package="courtr", mustWork=TRUE))) +ggplot2::ggtitle("Analyst") + 
  ggplot2::theme(plot.title = ggplot2::element_text(hjust = 0.5))
magick::image_ggplot(magick::image_read_svg(system.file("figures", "defendant.svg", package="courtr", mustWork=TRUE)))+ggplot2::ggtitle("Defendant") + 
  ggplot2::theme(plot.title = ggplot2::element_text(hjust = 0.5))
magick::image_ggplot(magick::image_read_svg(system.file("figures", "hazmat.svg", package="courtr", mustWork=TRUE)))+ggplot2::ggtitle("Hazmat") + 
  ggplot2::theme(plot.title = ggplot2::element_text(hjust = 0.5))
magick::image_ggplot(magick::image_read_svg(system.file("figures", "inmate.svg", package="courtr", mustWork=TRUE)))+ggplot2::ggtitle("Inmate") + 
  ggplot2::theme(plot.title = ggplot2::element_text(hjust = 0.5))
magick::image_ggplot(magick::image_read_svg(system.file("figures", "judge.svg", package="courtr", mustWork=TRUE)))+ggplot2::ggtitle("Judge") + 
  ggplot2::theme(plot.title = ggplot2::element_text(hjust = 0.5))
magick::image_ggplot(magick::image_read_svg(system.file("figures", "lawyer.svg", package="courtr", mustWork=TRUE)))+ggplot2::ggtitle("Lawyer") + 
  ggplot2::theme(plot.title = ggplot2::element_text(hjust = 0.5))
magick::image_ggplot(magick::image_read_svg(system.file("figures", "police.svg", package="courtr", mustWork=TRUE)))+ggplot2::ggtitle("Police") + 
  ggplot2::theme(plot.title = ggplot2::element_text(hjust = 0.5))
magick::image_ggplot(magick::image_read_svg(system.file("figures", "scientist.svg", package="courtr", mustWork=TRUE)))+ggplot2::ggtitle("Scientist") + 
  ggplot2::theme(plot.title = ggplot2::element_text(hjust = 0.5))

```


```{r,  echo=FALSE, message=FALSE, warning=FALSE, out.width = "24%", fig.show="hold"}

magick::image_ggplot(magick::image_read_svg(system.file("figures", "head1.svg", package="courtr", mustWork=TRUE)))+ggplot2::ggtitle("Option 1") + 
  ggplot2::theme(plot.title = ggplot2::element_text(hjust = 0.5))
magick::image_ggplot(magick::image_read_svg(system.file("figures", "head2.svg", package="courtr", mustWork=TRUE)))+ggplot2::ggtitle("Option 2") + 
  ggplot2::theme(plot.title = ggplot2::element_text(hjust = 0.5))
magick::image_ggplot(magick::image_read_svg(system.file("figures", "head3.svg", package="courtr", mustWork=TRUE)))+ggplot2::ggtitle("Option 3") + 
  ggplot2::theme(plot.title = ggplot2::element_text(hjust = 0.5))
magick::image_ggplot(magick::image_read_svg(system.file("figures", "head4.svg", package="courtr", mustWork=TRUE)))+ggplot2::ggtitle("Option 4") + 
  ggplot2::theme(plot.title = ggplot2::element_text(hjust = 0.5))
magick::image_ggplot(magick::image_read_svg(system.file("figures", "head5.svg", package="courtr", mustWork=TRUE)))+ggplot2::ggtitle("Option 5") + 
  ggplot2::theme(plot.title = ggplot2::element_text(hjust = 0.5))
magick::image_ggplot(magick::image_read_svg(system.file("figures", "head6.svg", package="courtr", mustWork=TRUE)))+ggplot2::ggtitle("Option 6") + 
  ggplot2::theme(plot.title = ggplot2::element_text(hjust = 0.5))
magick::image_ggplot(magick::image_read_svg(system.file("figures", "head7.svg", package="courtr", mustWork=TRUE)))+ggplot2::ggtitle("Option 7") + 
  ggplot2::theme(plot.title = ggplot2::element_text(hjust = 0.5))
magick::image_ggplot(magick::image_read_svg(system.file("figures", "head8.svg", package="courtr", mustWork=TRUE)))+ggplot2::ggtitle("Option 8") + 
  ggplot2::theme(plot.title = ggplot2::element_text(hjust = 0.5))
magick::image_ggplot(magick::image_read_svg(system.file("figures", "head9.svg", package="courtr", mustWork=TRUE)))+ggplot2::ggtitle("Option 9") + 
  ggplot2::theme(plot.title = ggplot2::element_text(hjust = 0.5))
magick::image_ggplot(magick::image_read_svg(system.file("figures", "head10.svg", package="courtr", mustWork=TRUE)))+ggplot2::ggtitle("Option 10") + 
  ggplot2::theme(plot.title = ggplot2::element_text(hjust = 0.5))
magick::image_ggplot(magick::image_read_svg(system.file("figures", "head11.svg", package="courtr", mustWork=TRUE)))+ggplot2::ggtitle("Option 11") + 
  ggplot2::theme(plot.title = ggplot2::element_text(hjust = 0.5))
magick::image_ggplot(magick::image_read_svg(system.file("figures", "head12.svg", package="courtr", mustWork=TRUE)))+ggplot2::ggtitle("Option 12") + 
  ggplot2::theme(plot.title = ggplot2::element_text(hjust = 0.5))
magick::image_ggplot(magick::image_read_svg(system.file("figures", "head13.svg", package="courtr", mustWork=TRUE)))+ggplot2::ggtitle("Option 13") + 
  ggplot2::theme(plot.title = ggplot2::element_text(hjust = 0.5))
magick::image_ggplot(magick::image_read_svg(system.file("figures", "head14.svg", package="courtr", mustWork=TRUE)))+ggplot2::ggtitle("Option 14") + 
  ggplot2::theme(plot.title = ggplot2::element_text(hjust = 0.5))
magick::image_ggplot(magick::image_read_svg(system.file("figures", "head16.svg", package="courtr", mustWork=TRUE)))+ggplot2::ggtitle("Option 16") + 
  ggplot2::theme(plot.title = ggplot2::element_text(hjust = 0.5))
magick::image_ggplot(magick::image_read_svg(system.file("figures", "head17.svg", package="courtr", mustWork=TRUE)))+ggplot2::ggtitle("Option 17") + 
  ggplot2::theme(plot.title = ggplot2::element_text(hjust = 0.5))
magick::image_ggplot(magick::image_read_svg(system.file("figures", "head18.svg", package="courtr", mustWork=TRUE)))+ggplot2::ggtitle("Option 18") + 
  ggplot2::theme(plot.title = ggplot2::element_text(hjust = 0.5))
magick::image_ggplot(magick::image_read_svg(system.file("figures", "head19.svg", package="courtr", mustWork=TRUE)))+ggplot2::ggtitle("Option 19") + 
  ggplot2::theme(plot.title = ggplot2::element_text(hjust = 0.5))

```
