library(shinytest2)

test_that("{shinytest2} recording: intro", {
  skip_on_cran()
  appdir <- system.file(package = "courtr", "Generic_App")
  app <- AppDriver$new(variant=platform_variant(),appdir, name = "intro")
  app$expect_values()
  app$click("informed")
  app$expect_values()
  app$set_inputs(uniqueID = "test")
  app$set_inputs(race = "American Indian or Alaska Native")
  app$set_inputs(gender = "Other/non-binary")
  app$set_inputs(age = "46 - 55")
  app$set_inputs(income = "$30,000 - $39,999")
  app$set_inputs(gunown = "Yes")
  app$set_inputs(guncomfort = "Neither Comfortable nor Uncomfortable")
  app$expect_values()
  app$click("demopage")
  app$set_inputs(state = "")
  app$set_inputs(educ = character(0))
  app$set_inputs(vote = character(0))
  app$set_inputs(poli = character(0))
  app$set_inputs(arrest = character(0))
  app$set_inputs(jury = character(0))
  app$set_inputs(jurycrim = "N/A")
  app$set_inputs(educ = "Some college")
  app$set_inputs(vote = "Republican")
  app$set_inputs(poli = "Very Liberal")
  app$set_inputs(arrest = "Yes")
  app$set_inputs(state = "AR")
  app$set_inputs(jury = "Yes")
  app$set_inputs(jurycrim = "No")
  app$expect_values()
  app$click("demopage")
  app$expect_values()
})

# test_that("{shinytest2} recording: notepad test", {
#   skip_on_cran()
#   appdir <- system.file(package = "courtr", "Generic_App")
#   app <- AppDriver$new(variant=platform_variant(),appdir, name = "notepad")
#   app$click("informed")
#   app$set_inputs(uniqueID = "res")
#   app$set_inputs(uniqueID = "tes")
#   app$set_inputs(uniqueID = "test")
#   app$set_inputs(race = "Other")
#   app$set_inputs(gender = "Woman")
#   app$set_inputs(age = "26 - 35")
#   app$set_inputs(income = "$10,000 - $19,999")
#   app$set_inputs(gunown = "Yes")
#   app$set_inputs(guncomfort = "Slightly Uncomfortable")
#   app$click("demopage")
#   app$set_inputs(state = "")
#   app$set_inputs(educ = character(0))
#   app$set_inputs(vote = character(0))
#   app$set_inputs(poli = character(0))
#   app$set_inputs(arrest = character(0))
#   app$set_inputs(jury = character(0))
#   app$set_inputs(jurycrim = "N/A")
#   app$set_inputs(educ = "4 year degree")
#   app$set_inputs(vote = "Democratic")
#   app$set_inputs(poli = "Very Liberal")
#   app$set_inputs(arrest = "Yes")
#   app$set_inputs(state = "AK")
#   app$set_inputs(jury = "Yes")
#   app$click("demopage")
#   app$set_inputs(notepad = "test1")
#   app$click("testimonypage")
#   app$expect_values()
#   app$set_inputs(`shinyjs-delay-d4bac3df5d847f846172133a2b86fc25` = 2000, allow_no_input_binding_ = TRUE)
#   app$click("testimonypage")
#   app$expect_values()
#   app$set_inputs(`shinyjs-delay-534f1a3d00b864b1ebdb2fa3be703c83` = 2000, allow_no_input_binding_ = TRUE)
#   app$set_inputs(notepad = "test12")
#   app$click("testimonypage")
#   app$set_inputs(`shinyjs-delay-40def21c9cab7e876bff653c2c11d6b2` = 2000, allow_no_input_binding_ = TRUE)
#   app$expect_values()
#   app$set_inputs(notepad = "")
#   app$set_inputs(notepad = "retes")
#   app$set_inputs(notepad = "retest")
#   app$click("testimonypage")
#   app$expect_values()
#   app$set_inputs(`shinyjs-delay-df0def680017dc0482a4b7bd845ffb54` = 2000, allow_no_input_binding_ = TRUE)
#   app$set_inputs(notepad = "retest ")
#   app$set_inputs(notepad = "retest again")
#   app$click("testimonypage")
#   app$set_inputs(`shinyjs-delay-2cb7d16c99df9d22f551262f3fd2dbab` = 2000, allow_no_input_binding_ = TRUE)
#   app$expect_values()
# })
