library(shinytest2)

test_that("{shinytest2} recording: Generic_App", {
  app <- AppDriver$new(variant = platform_variant(), name = "Generic_App", height = 533, 
      width = 979)
  app$expect_screenshot()
  app$click("informed")
  app$expect_screenshot()
  app$set_inputs(uniqueID = "test")
  app$set_inputs(race = "Hispanic")
  app$set_inputs(race = c("Asian", "Hispanic"))
  app$set_inputs(gender = "Woman")
  app$set_inputs(age = "56 - 65")
  app$set_inputs(income = "$60,000 - $69,999")
  app$set_inputs(gunown = "No")
  app$set_inputs(guncomfort = "Slightly Comfortable")
  app$click("demopage")
  app$set_inputs(state = "")
  app$set_inputs(educ = character(0))
  app$set_inputs(vote = character(0))
  app$set_inputs(poli = character(0))
  app$set_inputs(arrest = character(0))
  app$set_inputs(jury = character(0))
  app$set_inputs(jurycrim = "N/A")
  app$expect_screenshot()
  app$set_inputs(educ = "Less than high school")
  app$set_inputs(vote = "No consistent preference")
  app$set_inputs(poli = "Middle of the Road")
  app$set_inputs(arrest = "Yes")
  app$set_inputs(state = "AR")
  app$set_inputs(jury = "Yes")
  app$click("demopage")
  app$expect_screenshot()
  app$set_inputs(notepad = "test")
  app$click("testimonypage")
  app$set_inputs(`shinyjs-delay-3113eac00c314d5d13ab4d982b6a1c1c` = 2000, allow_no_input_binding_ = TRUE)
  app$expect_screenshot()
  app$click("testimonypage")
  app$set_inputs(`shinyjs-delay-85c575cc343f4e080392fc2f8cb9d6cd` = 2000, allow_no_input_binding_ = TRUE)
  app$set_inputs(notepad = "test 2")
  app$click("testimonypage")
  app$expect_screenshot()
  app$set_inputs(`shinyjs-delay-d03800f8cd0150caf0e7e1f03bb54989` = 2000, allow_no_input_binding_ = TRUE)
  app$click("testimonypage")
  app$set_inputs(`shinyjs-delay-1c75565422f2257a08a4fcd9da73b9bd` = 2000, allow_no_input_binding_ = TRUE)
  app$expect_screenshot()
  app$set_inputs(fixed_question1 = "Great.")
  app$click("questionpage")
  app$expect_screenshot()
  app$click("questionpage")
  app$set_inputs(fixed_question3 = "Click to continue")
  app$expect_screenshot()
  app$click("questionpage")
  app$set_inputs(hidden_slider = 50)
  app$set_inputs(hidden_slider = 70)
  app$expect_screenshot()
  app$click("questionpage")
  app$expect_screenshot()
  app$set_inputs(visible_slider = 31)
  app$click("questionpage")
  app$expect_screenshot()
  app$set_inputs(hidden_wlabels = 78)
  app$click("questionpage")
  app$set_inputs(chance_num = character(0))
  app$set_inputs(chance_denom = character(0))
  app$expect_screenshot()
  app$set_inputs(chance_num = 1)
  app$set_inputs(chance_denom = 2)
  app$set_inputs(chance_denom = 1)
  app$set_inputs(chance_denom = 2)
  app$click("questionpage")
  app$expect_screenshot()
  app$click("questionpage")
  app$expect_screenshot()
})
