library(shinytest2)

test_that("{shinytest2} recording: intro", {
  skip_on_cran()
  appdir <- system.file(package = "courtr", "Generic_App")
  app <- AppDriver$new(variant=platform_variant(),appdir, name = "intro")
  # app <- AppDriver$new(name = "intro", height = 533, width = 979)
  app$expect_values()
  app$click("informed")
  app$expect_values()
  app$set_inputs(uniqueID = "test")
  app$set_inputs(race = "American Indian or Alaska Native")
  app$set_inputs(gender = "Other/non-binary")
  app$set_inputs(age = "46 - 55")
  app$set_inputs(income = "$30,000 - $39,999")
  app$set_inputs(gunown = "Yes")
  app$set_inputs(guncomfort = "Neither Comfortable nor Uncomfortable")
  app$expect_values()
  app$click("demopage")
  app$set_inputs(state = "")
  app$set_inputs(educ = character(0))
  app$set_inputs(vote = character(0))
  app$set_inputs(poli = character(0))
  app$set_inputs(arrest = character(0))
  app$set_inputs(jury = character(0))
  app$set_inputs(jurycrim = "N/A")
  app$set_inputs(educ = "Some college")
  app$set_inputs(vote = "Republican")
  app$set_inputs(poli = "Very Liberal")
  app$set_inputs(arrest = "Yes")
  app$set_inputs(state = "AR")
  app$set_inputs(jury = "Yes")
  app$set_inputs(jurycrim = "No")
  app$expect_values()
  app$click("demopage")
  app$expect_values()
})


# test_that("{shinytest2} recording: Generic_App_start", {
#   skip_on_cran()
#   appdir <- system.file(package = "courtr", "Generic_App")
#   app <- AppDriver$new(variant=platform_variant(),appdir, name = "Generic_App")
#
#   app$expect_screenshot()
# })
#
# test_that("{shinytest2} recording: demographics", {
#   appdir <- system.file(package = "courtr", "Generic_App")
#   app <- AppDriver$new(variant = platform_variant(), appdir, name = "demographics", height = 533,
#                        width = 979)
#   app$click("informed")
#   app$expect_screenshot()
#   app$set_inputs(uniqueID = "test", wait_ = FALSE)
#   app$set_inputs(race = "Other", wait_ = FALSE)
#   app$set_inputs(gender = "Other/non-binary", wait_ = FALSE)
#   app$set_inputs(age = "56 - 65", wait_ = FALSE)
#   app$set_inputs(income = "$60,000 - $69,999", wait_ = FALSE)
#   app$set_inputs(gunown = "No", wait_ = FALSE)
#   app$set_inputs(guncomfort = "Slightly Comfortable", wait_ = FALSE)
#   app$click("demopage")
#   app$set_inputs(state = "", wait_ = FALSE)
#   app$set_inputs(educ = character(0), wait_ = FALSE)
#   app$set_inputs(vote = character(0))
#   app$set_inputs(poli = character(0))
#   app$set_inputs(arrest = character(0))
#   app$set_inputs(jury = character(0))
#   app$set_inputs(jurycrim = "N/A")
#   app$expect_screenshot()
#   app$set_inputs(educ = "High school graduate", wait_ = FALSE)
#   app$set_inputs(educ = "Doctorate", wait_ = FALSE)
#   app$set_inputs(vote = "Democratic", wait_ = FALSE)
#   app$set_inputs(poli = "Middle of the Road", wait_ = FALSE)
#   app$set_inputs(arrest = "Yes", wait_ = FALSE)
#   app$set_inputs(state = "AS", wait_ = FALSE)
#   app$set_inputs(jury = "Yes", wait_ = FALSE)
#   app$set_inputs(jurycrim = "No", wait_ = FALSE)
#   app$click("demopage")
#   app$expect_screenshot()
# })
